spring.application.name=videoplatform

#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=microservice289@gmail.com
spring.mail.password=vfigfmoucuqqqwfv
spring.mail.properties.mail.smpt.auth=true
spring.mail.properties.mail.smpt.starttls.enable=true
spring.mail.properties.mail.smpt.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true
#Database Configuration
spring.datasource.username=video_platform_8xib_user
spring.datasource.password=WmCd4Ua7zO4yVkaOmeWX1Vey8JrA5jxi
spring.datasource.url=jdbc:postgresql://dpg-cprf3ndumphs73c4fpi0-a.oregon-postgres.render.com:5432/video_platform_8xib

spring.jpa.hibernate.ddl-auto=update

server.port=8080

aws.accessKeyId=YOUR_ACCESS_KEY_ID
aws.secretKey=YOUR_SECRET_ACCESS_KEY
aws.region=YOUR_BUCKET_REGION
aws.s3.bucket=YOUR_BUCKET_NAME