spring.application.name=videoplatform

#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=irafiatu44@gmail.com
spring.mail.password=opomiavqqnepejrn
spring.mail.properties.mail.smpt.auth=true
spring.mail.properties.mail.smpt.starttls.enable=true
spring.mail.properties.mail.smpt.starttls.required=true
spring.mail.properties.mail.smpt.ssl.trust=smtp.gmail.com
spring.mail.properties.smtp.connectiontimeout=5000
spring.mail.properties.smtp.timeout=5000

#Database Configuration
spring.datasource.username=video_platform_8xib_user
spring.datasource.password=WmCd4Ua7zO4yVkaOmeWX1Vey8JrA5jxi
spring.datasource.url=jdbc:postgresql://dpg-cprf3ndumphs73c4fpi0-a.oregon-postgres.render.com:5432/video_platform_8xib

spring.jpa.hibernate.ddl-auto=update

server.port=8080