spring.application.name=videoplatform


spring.datasource.username=video_platform_8xib_user
spring.datasource.password=WmCd4Ua7zO4yVkaOmeWX1Vey8JrA5jxi
spring.datasource.url=jdbc:postgresql://dpg-cprf3ndumphs73c4fpi0-a.oregon-postgres.render.com:5432/video_platform_8xib

spring.jpa.hibernate.ddl-auto=update

server.port=8080