package com.videoplatform.videoplatform.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@Entity
@Table(name = "video")
public class Video {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(nullable = false)
    private String title;

    @Column
    private String description;

    @Getter
    @Setter
    @Column(nullable = false)
    private String videoUrl;

    @Column
    private Long fileSize;

    @Column
    private LocalDateTime dateCreated;

    // Constructor with all fields except id
    public Video(String title, String description, String videoUrl, Long fileSize) {
        this.title = title;
        this.description = description;
        this.videoUrl = videoUrl;
        this.fileSize = fileSize;
        this.dateCreated = LocalDateTime.now();
    }

    // Getters and setters (generated by Lombok @Data)

    @PrePersist
    protected void onCreate() {
        this.dateCreated = LocalDateTime.now();
    }
}